# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from webdriver_manager.chrome import ChromeDriverManager
class TestSurfgoogle():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_surfgoogle(self):
    self.driver.get("https://www.google.com//")
    self.driver.set_window_size(1366, 728)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "APjFqb")))
    self.driver.find_element(By.ID, "APjFqb").click()
    self.driver.find_element(By.ID, "APjFqb").send_keys("kodlamaio")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "btnK")))
    self.driver.find_element(By.NAME, "btnK").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#rso > .MjjYud:nth-child(1) .LC20lb")))
    self.driver.find_element(By.CSS_SELECTOR, "#rso > .MjjYud:nth-child(1) .LC20lb").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Tüm Kurslar")))
    self.driver.find_element(By.LINK_TEXT, "Tüm Kurslar").click()
  
